server:
  port: 8761

eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10

management:
  security:
    enabled: false
spring:
  main:
    allow-bean-definition-overriding: true
  boot:
    admin:
      context-path: /admin
